### ISSUE TITLE
Control parameters for nlminb call to Inetgreated Sgen-LRP model

### ISSUE THREAD

**Issue by krHolt** [Pacific-salmon-assess/SalmonLRP_RetroEval#1]
In order to get coho SR-LRP model to converge in nlminb in phase 1 opt call in Run_Ricker_LRP(), I reverted back to a control specifications: 
nlminb(obj$par, obj$fn, obj$gr, control = list(eval.max = 1e5, iter.max = 1e5))

This had been changed to nlminb(obj$par, obj$fn, obj$gr, control = list(eval.max = 1e10, iter.max = 1e10)) to get chum case to converge.

@lukewarkentin  - do you still have convergence problems with control = list(eval.max = 1e5, iter.max = 1e5) for chum?  If so, we will need to make this a parameter specified when calling Run_Ricker_LRP().

**Comment by lukewarkentin** [comment]
I get convergence using control = list(eval.max = 1e5, iter.max = 1e5), so no need to make further adjustments.

**Comment by lukewarkentin** [comment]
@krHolt, I am having convergence issues again with the chum case study. Need more iterations to get alpha and beta parameters to converge. Do you want me to code in a variable to TMB_Inputs to specify n iterations? Or can it be changed to 1e10? I will see what I get if I just adjust one of these values.

**Comment by krHolt** [comment]
@lukewarkentin.  For some reason, the integrated model fits with the IF coho case study will not work when max.iter is set to 1e10.  I can't explain this and will need to do some more reading, but it seems that the best solution for now is for max.iter to be specified in TMB_Inputs so that it can be different for each case study.

**Comment by lukewarkentin** [comment]
Hi Kendra, I have added an argument in TMB_Inputs called extra_eval_iter which can be set to TRUE, this then makes an if statement that has 1e5 iterations and evaluations in LRPFunctions.r (lines 180-186)

`# Call optimization:`
`if(TMB_Inputs$extra_eval_iter==TRUE) # extra evaluations and iterations for chum case study to get convergence for Ricker parameters`
`opt <- nlminb(obj$par, obj$fn, obj$gr, control = list(eval.max = 1e10, iter.max = 1e10), upper = upper, lower=lower )`
`else`
`opt <- nlminb(obj$par, obj$fn, obj$gr, control = list(eval.max = 1e5, iter.max = 1e5), upper = upper, lower=lower )`

Do you want to check that your coho code works with not assigning the argument?

**Comment by krHolt** [comment]
Yes - it works once I add extra_eval_iter = FALSE to my TMB inputs.  Thanks!
