### ISSUE TITLE
Typo on BY/RY alignment (not consequential, but to be fixed)

### ISSUE THREAD

**Issue by carrieholt** [Pacific-salmon-assess/SalmonLRP_RetroEval#12]
In runFraserCoho_projLRP.r, line 73, 80, and 85-86, the escapement data are aligned by return year (assuming constant 3 year age-at-maturity), instead of brood year (which I think they should be, e.g., removing escapement data before BY 1998 not RY 1998). However, I don’t think this is consequential as neither CoEscpDat nor AggEscp are used in the projections. I would remove these lines though to avoid confusion, unless they are relevant to other functions??

**Comment by krHolt** [comment]
Agreed. I have removed these lines.
