### ISSUE TITLE
Hardcoded name for mcmc outputs"RickerSurv_mcmc.csv"

### ISSUE THREAD

**Issue by carrieholt** [Pacific-salmon-assess/SalmonLRP_RetroEval#14]
I think this line (line   43 of ProjLRP_Functions.r)

write.csv(mcmcOut, paste(scenInputDir,"RickerSurv_mcmc.csv", sep="/"), row.names=F)

should be changed to:
write.csv(mcmcOut, paste(scenInputDir, paste(BMmodel,"_mcmc.csv",sep=""), sep="/"), row.names=F)

I can go  ahead and to this, unless these is a reason it's hardcoded?

**Comment by krHolt** [comment]
This has been fixed to use BMmodel
