### ISSUE TITLE
extinctThresh  default in projection code = 0.0001

### ISSUE THREAD

**Issue by carrieholt** [Pacific-salmon-assess/SalmonLRP_RetroEval#16]
I think the default for extinctthesh should be set to 1,2, 10, or 100, given that I think the input values and 1/beta are in actually numbers of fish (not millions, as in Cam's analysis on Fraser sockeye). This will mean that CUs go extinct more often, especially under high harvest rates. I have tentatively set it to 10 for WCVI Chinook, as I think many of the stocks are naturally quite low.

**Comment by krHolt** [comment]
Thanks for finding this; increased to 10 for IF coho.
