### ISSUE TITLE
Specification of B_penalty_mu and B_penalty_sigma for LowAggPrior models

### ISSUE THREAD

**Issue by krHolt** [Pacific-salmon-assess/SalmonLRP_RetroEval#2]
@lukewarkentin - I have moved the specification of B_penalty_mu and B_penalty_sigma to the TMB_Inputs list.  Previously they were individual arguments passed to Run_Ricker_LRP().  You may need to make changes to your chum case study code to account for this.

**Comment by lukewarkentin** [comment]
Changes made to chum.
