### ISSUE TITLE
Scaling of low aggregate penalty now in LRPFunctions.r, "SR_HierRicker_Surv_LowAggPrior" now in LRPFunctions.r

### ISSUE THREAD

**Issue by lukewarkentin** [Pacific-salmon-assess/SalmonLRP_RetroEval#3]
@krHolt , I moved the scaling of the low aggregate abundance penalty mu and sigma to the LRPFunctions.r code, so that you don't have to put scale in the TMB_Inputs and then use /1000 to scale the B_penalty_mu and B_penalty_sigma. This might need some changes for RunFraserCoho.r and testLogisticPen.r code. 

I also put the getSD function in the helperFunctions.r code. 

I also noticed that the hierarchical model with survival and the low aggregate penalty ("SR_HierRicker_Surv_LowAggPrior") was not in the LRPFunctions.r code, but there was a TMB file for it. I added the "SR_HierRicker_Surv_LowAggPrior" model into the LRPFunctinos.r code in the places that I thought were right. Please let me know if that works.

**Comment by krHolt** [comment]
Thanks. I removed the scaling from the IFCoho testLogisticPen.r file, and all works fine.
