### ISSUE TITLE
Error running percentile benchmarks in runSouthCoastChum.r

### ISSUE THREAD

**Issue by krHolt** [Pacific-salmon-assess/SalmonLRP_RetroEval#6]
Made change to runAnnualRetro() arguments in 'runSouthCoastChum.r' for percentile LRPs so that it will work with recent code updates, but am unable to fully test if they work due to error at line 236 in 'runSouthCoastChum.r'.  

Error message: "cannot open file 'DataOut/AnnualRetrospective/Bin.Percentile_noCUinfill_60/annualRetro_perc_benchmarks.csv': No such file or directory"

@lukewarkentin - can you test if these changes work?

**Comment by lukewarkentin** [comment]
Yes, these changes work.
